### ISSUE TITLE
Add documentation for HTML Tags

### ISSUE THREAD

**Issue by devrihan** [devrihan/TwittMe#3]
Add documentation explaining about different HTML tags that we use in building websites

**Comment by dev1abhi** [comment]
Please assign this to me. @devrihan

**Comment by Vivek789658** [comment]
HTML (Hypertext Markup Language) is the standard language for creating web pages. Here's a brief overview of some common HTML tags:

<html>: Defines the root of an HTML document.
<head>: Contains metadata about the document, like the title and linked stylesheets.
<title>: Sets the title of the web page displayed in the browser's tab.
<meta>: Provides additional information about the document, such as character encoding.
<link>: Links to external resources like stylesheets.
<style>: Embeds CSS (Cascading Style Sheets) directly within the HTML document.
<script>: Embeds JavaScript for client-side scripting.
<body>: Contains the visible content of the web page.
<h1>, <h2>, ... <h6>: Headings, with <h1> being the highest level and <h6> the lowest.
<p>: Defines a paragraph of text.
<a>: Creates hyperlinks to other web pages or resources.
<img>: Embeds images.
<ul>: Defines an unordered (bulleted) list.
<ol>: Defines an ordered (numbered) list.
<li>: Represents a list item within <ul> or <ol>.
<div>: A generic container for grouping and styling elements.
<span>: A generic inline container for styling text or elements.
<table>: Defines a table.
<tr>: Represents a table row.
<td>: Defines a table cell within a row.
<form>: Sets up an HTML form for user input.
<input>: Creates form input fields like text boxes, checkboxes, and radio buttons.
<button>: Defines a clickable button in a form.
<label>: Labels form elements for better user understanding.
<textarea>: Creates a multi-line text input field.
These are just a few of the many HTML tags available. Each tag serves a specific purpose and can be combined to structure and style web content. Learning how to use these tags effectively is essential for web development.




Plese Assign @devrihan

**Comment by Vivek789658** [comment]
Please Assign this to me @devrihan
